"""Initial clean migration

Revision ID: 0df4bfe34bbf
Revises: 5981b52606c8
Create Date: 2026-09-12 16:42:13.316558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df4bfe34bbf'
down_revision: Union[str, Sequence[str], None] = '5981b52606c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_city_name", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint("uq_city_name", type_='unique')

    # ### end Alembic commands ###
