"""Initial migration

Revision ID: 5b4a9f8170d6
Revises: 
Create Date: 2026-09-14 09:53:24.936758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4a9f8170d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_id'), ['id'], unique=False)

    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperature_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperature_id'))

    op.drop_table('temperature')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_id'))

    op.drop_table('city')
    # ### end Alembic commands ###
