"""Initial clean migration

Revision ID: dadd194e60b8
Revises: f268acb8ccfb
Create Date: 2026-09-12 17:02:08.565255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dadd194e60b8"
down_revision: Union[str, Sequence[str], None] = "f268acb8ccfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temperature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("date_time", sa.DateTime(), nullable=True),
        sa.Column("temperature", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_temperature_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temperature_id"))

    op.drop_table("temperature")
    # ### end Alembic commands ###
